### ISSUE TITLE
doctrine:phpcr:repository:init stops working when cache enabled

### ISSUE THREAD

**Issue by r0ssIV** [liip/LiipDoctrineCacheBundle#13]
To reproduce, enable LiipDoctrineCacheBundle in sandbox according to docs
"Finally uncomment the caches settings in the phpcr.yml as well as the liip_doctrine_cache settings in app/config/config.yml."

Then delete app.sqlite and try from beginning:
php app/console doctrine:database:create - OK
php app/console doctrine:phpcr:init:dbal - OK

php app/console doctrine:phpcr:repository:init - FAILURE

Successfully registered system node types.

  [PHPCR\PathNotFoundException]
  Item / not found in workspace default

  [PHPCR\ItemNotFoundException]
  Item / not found in workspace default

it fails to create the / node.

Lukas, maybe you can get it fixed.

**Comment by pstephenson02** [comment]
@lsmith77 Can you elaborate a bit more on what the issue is? I'm running into this problem in my test suite. We're using the phpcr_nodes cache provider here, then using the LiipFunctionalTestBundle to load regular ORM fixtures, and _then_ I need to initialize the phpcr repo with `doctrine:phpcr:init:dbal` and `doctrine:phpcr:repository:init`. I tried disabling the cache but had no luck... Thanks in advance

**Comment by lsmith77** [comment]
basically if you clear the database but not the cache, then you can run into inconsistencies. however if you disabled the cache, then this issue cannot affect you.
